# Bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Upload dos dados

In [2]:
olist_orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
olist_order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
olist_customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")
olist_products = pd.read_csv("../data/raw/olist_products_dataset.csv")
olist_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
olist_geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")


customer_cluster = pd.read_csv("../data/cluster_info.csv")

# Juntando todas as bases com a base cluster

In [10]:
customers = customer_cluster.merge(olist_customers, how='inner', on='customer_unique_id')
customers_orders = customers.merge(olist_orders, how='inner', on='customer_id')
customers_orders_items = customers_orders.merge(olist_order_items, how='inner', on='order_id')

customers_products = customers_orders_items.merge(olist_products, how='inner', on='product_id')

customers_reviews = customers_orders.merge(olist_reviews, how='inner', on='order_id')

In [7]:
customers_products = customers_products.drop(columns='Unnamed: 0')

In [8]:
customers_products[customers_products.cluster == 2].describe()

,total_value,quant_orders,cluster,customer_zip_code_prefix,order_item_id,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,4637.000000,4637.000000,4637.0,4637.000000,4637.000000,4637.000000,4637.000000,4594.000000,4594.000000,4594.000000,4636.000000,4636.000000,4636.000000,4636.000000
mean,1104.180429,1.025663,2.0,40646.959457,1.845374,667.869500,44.575327,48.487810,1167.882891,2.357205,6891.556730,38.280630,28.007334,29.290768
std,825.938046,0.158145,0.0,29980.458330,1.871989,570.215537,42.514247,9.695088,880.110632,1.757992,7993.448544,20.409888,19.760714,15.940897
min,587.500000,1.000000,2.0,1006.000000,1.000000,11.500000,0.000000,14.000000,60.000000,1.000000,50.000000,12.000000,2.000000,8.000000
25%,689.520000,1.000000,2.0,13485.000000,1.000000,199.990000,19.950000,42.000000,504.000000,1.000000,800.000000,20.000000,13.000000,16.000000
50%,862.390000,1.000000,2.0,33400.000000,1.000000,599.650000,29.450000,51.000000,954.000000,2.000000,2750.000000,33.000000,20.000000,25.000000
75%,1246.950000,1.000000,2.0,68485.000000,2.000000,859.900000,53.610000,57.000000,1485.000000,3.000000,11850.000000,50.000000,40.000000,39.000000
max,13664.080000,2.000000,2.0,99700.000000,20.000000,6735.000000,409.680000,64.000000,3992.000000,14.000000,30000.000000,105.000000,105.000000,105.000000

In [9]:
# categoria de produtos do cluster 2
customers_products[customers_products.cluster == 2].product_category_name.value_counts()

product_category_name
relogios_presentes                                515
informatica_acessorios                            401
beleza_saude                                      344
moveis_escritorio                                 300
automotivo                                        246
moveis_decoracao                                  218
cool_stuff                                        211
esporte_lazer                                     201
pcs                                               198
utilidades_domesticas                             190
ferramentas_jardim                                190
cama_mesa_banho                                   170
bebes                                             133
eletroportateis                                   110
instrumentos_musicais                             105
telefonia                                         104
brinquedos                                        102
construcao_ferramentas_construcao                 101
eletrodomesticos_2                                 61
consoles_games                                     54
moveis_sala                                        52
pet_shop                                           52
climatizacao                                       44
portateis_casa_forno_e_cafe                        43
telefonia_fixa                                     42
agro_industria_e_comercio                          39
casa_construcao                                    38
eletronicos                                        37
eletrodomesticos                                   32
moveis_cozinha_area_de_servico_jantar_e_jardim     31
construcao_ferramentas_seguranca                   21
sinalizacao_e_seguranca                            21
perfumaria                                         19
papelaria                                          19
audio                                              18
bebidas                                            16
fashion_bolsas_e_acessorios                        15
construcao_ferramentas_jardim                      13
malas_acessorios                                   12
industria_comercio_e_negocios                      11
construcao_ferramentas_iluminacao                  10
casa_conforto                                       9
market_place                                        9
construcao_ferramentas_ferramentas                  7
moveis_quarto                                       6
artigos_de_natal                                    6
portateis_cozinha_e_preparadores_de_alimentos       3
livros_interesse_geral                              3
alimentos_bebidas                                   2
cine_foto                                           2
musica                                              2
dvds_blu_ray                                        2
livros_importados                                   1
artigos_de_festas                                   1
tablets_impressao_imagem                            1
artes                                               1
Name: count, dtype: int64

In [11]:
customers_reviews

,Unnamed: 0,customer_unique_id,total_value,quant_orders,cluster,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,...,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,0,0000366f3b9a7992bf8c76cfdf3221e2,141.90,1,0,fadbb3709178fc513abc1b2670aa1ad2,7787,cajamar,SP,e22acc9c116caa3f2b7121bbb380d08e,...,2018-05-10 11:11:18,2018-05-12 08:18:00,2018-05-16 20:48:37,2018-05-21 00:00:00,13359f48c3c7e41a2b8afca340937eeb,5,Super Recomendo,"Adorei a cortina, ficou linda na minha sala, e...",2018-05-17 00:00:00,2018-05-21 13:44:48
1,1,0000b849f77a49e4a4ce2b2a4ca5be3f,27.19,1,0,4cb282e167ae9234755102258dd52ee8,6053,osasco,SP,3594e05a005ac4d06a72673270ef9ec9,...,2018-05-07 18:25:44,2018-05-09 12:18:00,2018-05-10 18:02:42,2018-05-15 00:00:00,e383e10e36a765f04f752a37c1674e43,4,NaN,NaN,2018-05-11 00:00:00,2018-05-11 22:29:25
2,2,0000f46a3911fa3c0805444483337064,86.22,1,0,9b3932a6253894a02c1df9d19004239f,88115,sao jose,SC,b33ec3b699337181488304f362a6b734,...,2017-03-10 21:05:03,2017-03-13 12:58:30,2017-04-05 14:38:47,2017-04-07 00:00:00,d89cb4217c23008b141e66c3160de8a4,3,NaN,NaN,2017-04-06 00:00:00,2017-04-07 01:19:44
3,3,0000f6ccb0745a6a4b88665a16c9f078,43.62,1,0,914991f0c02ef0843c0e7010c819d642,66812,belem,PA,41272756ecddd9a9ed0180413cc22fb6,...,2017-10-12 20:49:17,2017-10-13 20:08:19,2017-11-01 21:23:05,2017-11-13 00:00:00,6f22e4ad2cd9e0d40c5842e4787b4321,4,NaN,Bom vendedor,2017-11-02 00:00:00,2017-11-03 00:17:51
4,4,0004aac84e0df4da2b147fca70cf8255,196.89,1,0,47227568b10f5f58a524a75507e6992c,18040,sorocaba,SP,d957021f1127559cd947b62533f484f7,...,2017-11-14 20:06:52,2017-11-16 19:52:10,2017-11-27 23:08:56,2017-12-05 00:00:00,880a77e7dd4e496969f138f974cc44a1,5,NaN,NaN,2017-11-28 00:00:00,2017-12-02 22:29:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98128,94978,fffcf5a5ff07b0908bd4e2dbc735a684,2067.42,1,2,74be082247cd677a147d83ee670e9d53,55250,sanharo,PE,725cf8e9c24e679a8a5a32cb92c9ce1e,...,2017-06-08 21:15:16,2017-06-23 13:03:27,2017-07-06 09:22:00,2017-08-02 00:00:00,bf0bcc92778d81c81f4e270732edcee6,5,NaN,NaN,2017-07-07 00:00:00,2017-07-11 11:20:05
98129,94979,fffea47cd6d3cc0a88bd621562a9d061,84.58,1,0,0ecf8e0a08148af0bf313184f167670a,44054,feira de santana,BA,c71b9252fd7b3b263aaa4cb09319a323,...,2017-12-10 20:16:20,2017-12-21 16:27:01,2018-01-09 22:28:20,2018-01-12 00:00:00,b194b439cde1d72277a2d0545a5de82e,4,NaN,NaN,2018-01-10 00:00:00,2018-01-15 11:51:59
98130,94980,ffff371b4d645b6ecea244b27531430a,112.46,1,0,27f584b0f1dc4e610065c240f68b6be0,78552,sinop,MT,fdc45e6c7555e6cb3cc0daca2557dbe1,...,2017-02-07 16:02:44,2017-02-08 10:04:37,2017-02-22 12:45:04,2017-03-24 00:00:00,11c3e9036551ef3649c3c781f9d24e1d,5,NaN,NaN,2017-02-23 00:00:00,2017-02-25 15:03:21
98131,94981,ffff5962728ec6157033ef9805bacc48,133.69,1,0,832a3b0254347d409512ae92eaf154a6,29460,bom jesus do norte,ES,94d3ee0bc2a0af9d4fa47a4d63616e8d,...,2018-05-02 15:58:47,2018-05-03 16:45:00,2018-05-14 11:54:26,2018-05-28 00:00:00,9afc85900a86fb8df3c31721f1869756,5,********,"excelente lojas, a posterior vou fazer uma aqu...",2018-05-15 00:00:00,2018-05-17 15:16:20
98132,94982,ffffd2657e2aad2907e67c3e9daecbeb,71.56,1,0,70bc4d9cf2bbeea3f7b09798370f5884,83608,campo largo,PR,f79a35da168301ae56922475da21117b,...,2017-05-03 15:15:13,2017-05-04 12:05:22,2017-05-10 09:33:48,2017-05-26 00:00:00,c226e4b3cc6f681717f77f5c15a0bafd,5,NaN,NaN,2017-05-11 00:00:00,2017-05-13 10:55:24

In [14]:
customers_reviews[customers_reviews.cluster == 2].describe()

,Unnamed: 0,total_value,quant_orders,cluster,customer_zip_code_prefix,review_score
count,3167.000000,3167.000000,3167.000000,3167.0,3167.000000,3167.000000
mean,47500.281023,1052.390142,1.017682,2.0,40437.536470,3.930218
std,27738.439808,639.666845,0.131815,0.0,29737.252233,1.494312
min,126.000000,587.500000,1.000000,2.0,1006.000000,1.000000
25%,23529.500000,680.505000,1.000000,2.0,13468.500000,3.000000
50%,47783.000000,840.480000,1.000000,2.0,32600.000000,5.000000
75%,71695.500000,1218.060000,1.000000,2.0,66360.000000,5.000000
max,94978.000000,13664.080000,2.000000,2.0,99700.000000,5.000000

In [15]:
# cluster que fez mais pedidos
customers_reviews[customers_reviews.cluster == 1].describe()

,Unnamed: 0,total_value,quant_orders,cluster,customer_zip_code_prefix,review_score
count,868.000000,868.000000,868.000000,868.0,868.000000,868.000000
mean,50632.305300,529.456210,3.776498,1.0,35154.960829,4.342166
std,26057.653603,467.572967,2.040716,0.0,29788.931168,1.169280
min,1082.000000,46.860000,3.000000,1.0,1239.000000,1.000000
25%,29646.000000,243.890000,3.000000,1.0,11065.000000,4.000000
50%,52352.000000,406.865000,3.000000,1.0,24230.000000,5.000000
75%,73850.000000,704.150000,4.000000,1.0,59183.250000,5.000000
max,94824.000000,4655.880000,16.000000,1.0,97670.000000,5.000000

In [17]:
# clientes que fez 1 pedido mas não geraram tanto faturamento
customers_products[customers_products.cluster == 0].product_category_name.value_counts()

product_category_name
cama_mesa_banho                                  9823
beleza_saude                                     8744
esporte_lazer                                    7722
moveis_decoracao                                 7305
informatica_acessorios                           6843
                                                 ...
portateis_cozinha_e_preparadores_de_alimentos      12
pc_gamer                                            7
fashion_roupa_infanto_juvenil                       7
pcs                                                 4
seguros_e_servicos                                  2
Name: count, Length: 73, dtype: int64

In [18]:
customers_reviews[customers_reviews.cluster == 0].describe()

,Unnamed: 0,total_value,quant_orders,cluster,customer_zip_code_prefix,review_score
count,88500.000000,88500.000000,88500.0,88500.0,88500.000000,88500.000000
mean,47490.740734,130.368074,1.0,0.0,35109.466927,4.116893
std,27418.135382,98.952972,0.0,0.0,29817.035633,1.317245
min,0.000000,9.590000,1.0,0.0,1003.000000,1.000000
25%,23739.750000,60.850000,1.0,0.0,11320.000000,4.000000
50%,47490.500000,102.030000,1.0,0.0,24365.000000,5.000000
75%,71227.250000,167.090000,1.0,0.0,58748.000000,5.000000
max,94982.000000,587.090000,1.0,0.0,99990.000000,5.000000

In [19]:
customers_reviews[customers_reviews.cluster == 3].describe()

,Unnamed: 0,total_value,quant_orders,cluster,customer_zip_code_prefix,review_score
count,5598.000000,5598.000000,5598.0,5598.0,5598.000000,5598.000000
mean,46915.847803,270.479552,2.0,3.0,33835.131833,4.140050
std,27107.809436,197.403190,0.0,0.0,29820.365428,1.321893
min,106.000000,35.940000,2.0,3.0,1005.000000,1.000000
25%,23964.000000,140.810000,2.0,3.0,9710.000000,4.000000
50%,46324.000000,213.360000,2.0,3.0,22780.000000,5.000000
75%,70091.750000,336.210000,2.0,3.0,52067.500000,5.000000
max,94937.000000,1381.410000,2.0,3.0,99750.000000,5.000000

In [20]:
customers_products[customers_products.cluster == 3].product_category_name.value_counts()

product_category_name
cama_mesa_banho                  935
moveis_decoracao                 707
esporte_lazer                    577
beleza_saude                     490
informatica_acessorios           463
                                ...
portateis_casa_forno_e_cafe        1
la_cuisine                         1
pcs                                1
fashion_roupa_infanto_juvenil      1
fashion_esporte                    1
Name: count, Length: 68, dtype: int64